### ISSUE TITLE
FieldChangeSummary does not catch removal/falsification of properties

### ISSUE THREAD

**Issue by John-Youngblood** [scatcher/angular-point#16]
When a `FieldChangeSummary` is constructed it compares the properties between the two `ListItem`s given (`newerVersion`,`previousVersion`)  to find differences. However it only pulls the property keys/names from the `newerVersion` and due to how these `ListItems` are being passed to the `FieldChangeSummary` constructor, any property that has a "falsy" value (e.g. `""`, `false`, `null`, etc.) is not included in the `ListItem` and therefore is skipped over when looking for changes. Here is an example:

Old Version of a `ListItem`:
```
{
  title: "3.01.01",
  ucr: true,
  specLetter: "ABC"
}
```
if we set `ucr` to `false` and `specLetter` to `""`, this is how that newer version of the `ListItem` would look (at least when passed to the `FieldChangeSummary`):
```
{
  title: "3.01.01"
}
```

Now here is the `FieldChangeSummary` constructor code:
https://github.com/scatcher/angular-point/blob/9acd7bf3d0149d891021945749f32565f7d0c1ef/src/factories/apListItemVersionFactory.ts#L113-L136

Because the `_.each` on line 115 only loops through `newerVersion`'s properties, then in the above example the changes to `ucr` and `specLetter` would not be seen.

Two possible solutions are:
- Make sure `ListItem`s always include all read-only properties when passed to `FieldChangeSummary`'s constructor even if their value is `false`, `""`, or `null` 

or if that is a necessary feature for `ListItem`s to have, then instead:

- Change the `FieldChangeSummary` constructor code to also loop through `previousVersion`'s properties to look for changes.

**Comment by John-Youngblood** [comment]
I could not push a new branch with a fix I implemented, but here it is (this would replace the current constructor for `FieldChangeSummary`):
```typescript
constructor(newerVersion: ListItem<T> | any, previousVersion: ListItem<T> | Object | any = <ListItem<T>>{}) {
    /** Loop through each of the properties on the newer list item */
    _.each(newerVersion, (val, propertyName: string) => {
        const fieldDefinition = newerVersion.getFieldDefinition(propertyName);
        /** Only log non-readonly fields that aren't the same */
        if (
            fieldDefinition &&
            !fieldDefinition.readOnly &&
            JSON.stringify(newerVersion[propertyName]) !== JSON.stringify(previousVersion[propertyName])
        ) {
            let fieldChange = new FieldChange(propertyName, fieldDefinition, newerVersion, previousVersion);
            if (fieldChange.newValue !== fieldChange.oldValue) {
                /** This field has changed */
                this.fieldsChanged[propertyName] = fieldChange;
            }
        }
    });

    _.each(previousVersion, (val, propertyName: string) => {
        const fieldDefinition = previousVersion.getFieldDefinition(propertyName);
        /** Only log non-readonly fields that aren't the same */
        if (
            this.fieldsChanged[propertyName] === undefined && //only check for changes not already identified
            fieldDefinition &&
            !fieldDefinition.readOnly &&
            JSON.stringify(previousVersion[propertyName]) !== JSON.stringify(newerVersion[propertyName])
        ) {
            let fieldChange = new FieldChange(propertyName, fieldDefinition, newerVersion, previousVersion);
            if (fieldChange.newValue !== fieldChange.oldValue) {
                /** This field has changed */
                this.fieldsChanged[propertyName] = fieldChange;
            }
        }
    });

    this.changeCount = _.keys(this.fieldsChanged).length;
}
```

**Comment by John-Youngblood** [comment]
Looking into this a bit further, and it looks like technically its the `ListItemVersion` object thats having its "falsy" valued properties being stripped (though properties that are empty arrays are still present) when passed to the `VersionSummary` constructor, but they are extensions of `ListItem` and `FieldChangeSummary` respectively and `VersionSummary`'s constructor makes a `super` call to `FieldChangeSummary` so the above code change to `FieldChangeSummary`'s constructor fixes the above issue.

**Comment by scatcher** [comment]
Nice work on the deep dive 🏆!  I added you as a collaborator so you should be good to create a PR.
